services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: zwpa
    environment:
      ZWPA_DATABASE_HOST: "postgres"
      ZWPA_DATABASE_PORT: "5432"
      ZWPA_DATABASE_DATABASE: "${ZWPA_DATABASE_DATABASE}"
      ZWPA_DATABASE_LOGIN: "${ZWPA_DATABASE_LOGIN}"
      ZWPA_DATABASE_PASSWORD: "${ZWPA_DATABASE_PASSWORD}"
      ZWPA_ADMIN_LOGIN: "${ZWPA_ADMIN_LOGIN}"
      ZWPA_ADMIN_PASSWORD: "${ZWPA_ADMIN_PASSWORD}"
      ZWPA_CART_MANAGER_HOST: "cart_manager"
      ZWPA_CART_MANAGER_PORT: "${ZWPA_CART_MANAGER_PORT}"
      ZWPA_CART_MANAGER_ACCESS_KEY: "${ZWPA_CART_MANAGER_ACCESS_KEY}"
    ports:
      - ${ZWPA_WEBSERVER_PORT}:8000
    depends_on:
      - postgres
  postgres:
    image: "postgres:11"
    environment:
      POSTGRES_PASSWORD: "${ZWPA_DATABASE_PASSWORD}"
    ports:
      - 5432:5432
  cart_manager:
    build:
      context: .
      dockerfile: Dockerfile
      target: cart_manager
    environment:
      ACCESS_TOKEN: "access"
    ports:
      - ${ZWPA_CART_MANAGER_PORT}:8050
